### ISSUE TITLE
Toolbar control

### ISSUE THREAD

**Issue by dbuerer** [loopindex/ckeditor-track-changes#10]
I have a custom specific tool bar configuration for CKEDitor.  I am trying to setup my configuration so that TOGGLE_SHOW is the only icon in the toolbar for normal users, and, for the moderator they get TOGGLE_SHOW, ACCEPT_ALL, ACCEPT_ONE, REJECT_ALL, REJECT_ONE

I may be doing something wrong if so my apologies i am still very new to CKEDitor but learning rapidly...however...., I expect that i can define the toolbar like this:
<CODE>
toolbar: [
        { name: 'document', groups: [ 'mode', 'document', 'doctools' ], items: [ 'savebtn', 'Preview', 'Print', '-', 'Templates' ] },
.....
.....

```
    { name: 'liteTB', groups: ['lite'], items: ['TOGGLE_SHOW']}
]
```

</CODE>

and that doesn't work, in fact none of the buttons show up at all.
I've tried also listing the commands in config.lite.commands and that doesn't seem to work.  

Suggestions?

**Comment by gsinha** [comment]
This worked for me:
{name: "lite", items: ['lite-toggletracking', 'lite-toggleshow', 'lite-acceptall', 'lite-rejectall', 'lite-acceptone','lite-rejectone'] }

Maybe someone gets benefit from this.
