### ISSUE TITLE
when tracking is off inserthtml is converted attributes by ckeditor

### ISSUE THREAD

**Issue by Amara-Balakrishna1** [loopindex/ckeditor-track-changes#102]
ckeditor.insertHTML('table tr td mousedown="customfunction()">cheking for mousedown td tr table).

converted after pasting table tr td data-cke-pa-mousedown="customfunction()">cheking for mousedown td tr table..and event not triggered on mouse down how to trigger custom function on mousedown?

**Comment by imdfl** [comment]
Hi

The phenomenon you've described is related to the ckeditor advanced content filtering (ACF), not to LITE.
You need to tell ckeditor that td elements can contain a mousedown attribute. If you don't, ckeditor normalizes all attributes to live in the data-cke "namespace". Take a look at our code in plugin.js, toward the end, in the function _setPluginFeatures. It's not trivial use but you may learn from it how to interact with the ACF. Or check the docs:
http://docs.ckeditor.com/#!/guide/dev_advanced_content_filter
