### ISSUE TITLE
Editor Closes and/or Exception Thrown when Removing Characters Preceding Hidden Changes

### ISSUE THREAD

**Issue by eldricht** [loopindex/ckeditor-track-changes#118]
# Environment
CKEditor Demo Page (http://www.loopindex.com/lite/demo/), Internet Explorer 11

# Reproduction
From demo page:

1. Enter 'test' (change will be tracked).
2. Place cursor immediately before the first 't'.
3. Click the 'Hide Tracked Changes' control.
4. Repeatedly tap backspace.

# Result

At times, this process causes CKEditor to lose focus (meaning a quick double-tap of the backspace key can activate the browser's default 'navigate back' behavior).  Other times, this process throws a null/undefined reference error ("unable to get property 'startPath' of undefined or null reference").  This seems to depend on the where the cursor is when the issue manifests (i.e., if some characters are deleted before 'Hide Tracked Changes' is clicked, the undefined reference error
will occur).

**Comment by imdfl** [comment]
LITE's support for IE (all versions) is limited and untested. There have been too many issues with the selection implementation.
