### ISSUE TITLE
ICE Plugin init error when i used requirejs

### ISSUE THREAD

**Issue by atmegavn** [loopindex/ckeditor-track-changes#124]
hi, i download the sample code and it run good. but when i run it on my project use requirejs then ICE plugin can not init. i think the main reason is ICE plugin is not AMD style.
how do you think?

**Comment by imdfl** [comment]
Sounds interesting. Can you please provide some code to show how you use requirejs and how this affects the loading of the plugin and/or ckeditor?

**Comment by atmegavn** [comment]
hi, thank you for reply
my codes simple here

```
<div id="editor">
    <h1>Hello world!</h1>
    <p>I am an instance of CKEditor</p>
</div>

<script>
    require(['ckeditor'], function () { 
        CKEDITOR.replace('editor');
    })
</script>
```
and this is result
![image](https://user-images.githubusercontent.com/5243990/28910965-fed2cacc-7858-11e7-97cf-0377b1b9b74c.png)

i think requirejs loaded ckeditor successful, but ckeditor can not load ICE plugin via requirejs

**Comment by imdfl** [comment]
Thanks for the info. Can you please share you essential script includes, so that I can reconstruct the problem on my machine?

**Comment by atmegavn** [comment]
so i tried to delete some text then my browser console add more error like this
![image](https://user-images.githubusercontent.com/5243990/28911111-a98df310-7859-11e7-9d3c-f40374698d38.png)

**Comment by atmegavn** [comment]
thanks, i am going to build another simple project for you because my project is too big

**Comment by imdfl** [comment]
Thanks. Maybe that's not necessary, I just need to know how and where you include requirejs (and which version) and how ckeditor is required - does this come out of the box or do you need special configuration.

**Comment by atmegavn** [comment]
This is how I configure requirejs

```javascript
# The config.js file:
require.config({
    baseUrl: 'lib',
    paths: {
        hd: '../js/hd', # app js file
        'domReady': 'requirejs_domReady/domReady',
        'jquery': "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery",
        'jquery.validate': 'jquery_validation/dist/jquery.validate',
        'jquery.validate.unobtrusive': 'jquery_validation_unobtrusive/jquery.validate.unobtrusive',
        'toolkit': "dashboard/dist/toolkit",
        'js.cookie': "js_cookie/src/js.cookie",
        'kendo': 'kendo/js',
        'kendo.all.min': 'kendo/js/kendo.all.min',
        'kendo.aspnetmvc.min': 'kendo/js/kendo.aspnetmvc.min',
        'kendo.timezones.min': 'kendo/js/kendo.timezones.min',
        'pako_deflate.min': 'kendo/js/pako_deflate.min',
        'ckeditor': 'ckeditor/ckeditor'
    },
    bundles: {
        'kendo.all.min': [
            # ... Bulde config for load kendo
        ]
    },
    shim: {
        'toolkit': ["jquery"],
        'jquery.validate': ['jquery'],
        'jquery.validate.unobtrusive': ['jquery.validate'],
        'ckeditor': ['jquery']
    }
});
```

```java script
# The main of requrejs
# Just force requriejs to load essential library

define(['jquery', 'js.cookie', 'toolkit', 'jquery.validate', 'jquery.validate.unobtrusive'], function ($, Cookies) {    
});
``` 

And on the head of page I load requirejs by:
```html
    <script src="~/js/config.js"></script>
    <script>
        require(['main']);
    </script>
```

When need to use ckeditor on page I load it by:
```html
<script>
    require(['ckeditor'], function () { 
        CKEDITOR.replace('editor');
    })
</script>
```

The ckeditor is load fine, but when calling `CKEDITOR.replace('editor');`, it's give me the error about.

**Comment by imdfl** [comment]
I finally found time to look at this. The problem stems from the rangy being the only part of the plugin that suppors amd. Therefore, when requirejs is used, rangy is no longer define in the global namespace. I hope to provide a solution soon, unless some1 beats me to it.

**Comment by imdfl** [comment]
Please check out the latest version in master. I added code that loads rangy appropriately when requirejs is present. Make sure you config() requirejs with the correct path for "rangy" - it should be "ckeditor/plugins/lite/js/rangy-core", or something close depending on the location of ckeditor.

Please close this issue if the fix is satisfactory.

**Comment by atmegavn** [comment]
It's now working fine, thank you so much
