### ISSUE TITLE
Jump to next change option on right click menu

### ISSUE THREAD

**Issue by sekhar-88** [loopindex/ckeditor-track-changes#149]
If we want to jump to a next change that needs to be accepted/rejected we have to scroll all the way up and down if there are huge amount of text in the editor. 

So can we add 'jump to next change' to the right click popup menu , so that it would be easier.

For now is there a way we can do it programmatically ?

**Comment by imdfl** [comment]
The outline of the relevant code would be:
1. get the caret position from the editor (i.e. editor.getSelection().getRanges()[ 0 ])
2. Collect all the remaining tracked nodes (e.g. jQuery(editor.editable().$).find(".ice-ins, .ice-del")
3. Sort the nodes by their order, using the Element method `compareDocumentPosition()` or the jQuery method `closest()`
4. select the resulting node through ckeditor's api (if necessary, trigger the editor's `selectionChange `event to force LITE to refresh the commands' state).

**Comment by MDKrishnan** [comment]
1 st and 2nd points are ok.
how to do 3 and 4 th points by using lite plugin code
