### ISSUE TITLE
When track changes is on I can't add a formula using MathJax

### ISSUE THREAD

**Issue by esglickman** [loopindex/ckeditor-track-changes#156]
I ckeditor 4 in my companies software and recently we've discovered a bug with the track changes using your Lite plugin and the MathJax plugin. When I am tracking changes I get an error in the console when i try to add a fomula. I dont understand what the error is because the code is minified and compiled but it says: "c is not a function". Any help you might have would be very appreciated.

**Comment by imdfl** [comment]
Hello @esglickman 
Development of LITE stopped about 3 years ago. LoopIndex has a commercial track changes plugin which offers a different tracking engine. It supports several common scenarios involving MathJax, tho there may be glitches due to the asynchronous, iframe-based nature of MathJax.
