### ISSUE TITLE
Turning Track changes on/off, hide/show and accept all is not working correctly

### ISSUE THREAD

**Issue by trifprog** [loopindex/ckeditor-track-changes#26]
Turning TC off/on and hiding/show is not working properly.    These are all recreated on your demo page.

Example 1:
I typed several sections in this document with Track Changes on and off, yet once you toggle it back on all areas are showing as tracked.

1. Typed section 1 & 2 with TC on
2. Turned TC off and typed Section 3 - everything displayed with no hilighting
3. Turned TC on and typed Section 4 - all new text shows as tracked with hilighting

Hiding and Turning Tracking off act the same - hiding and showing all new text - even the sectioned type when tracking was off

![image](https://cloud.githubusercontent.com/assets/6908839/3306052/28b67d06-f65d-11e3-92df-7d2d8688c397.png)

Example 2:

1. Typed sections 1 and 2, never turning TC off or hiding or any other actions.
2. Deleted text and then continued typing section 3 and 4.
3. Clicked Hide TC and sections 2 and 4 remain hilighted.  Turning on/off keeps 2 and 4 hilighted as well
4. Clicking Accept All Changes and 2 and 4 remain hilighted.

![image](https://cloud.githubusercontent.com/assets/6908839/3306177/80cc4eb6-f65e-11e3-8182-a3281c71ffba.png)

Hide Track Changes: 
![image](https://cloud.githubusercontent.com/assets/6908839/3306195/a724a964-f65e-11e3-91b9-0a0906bd8ed4.png)

After Accept All Changes:
![image](https://cloud.githubusercontent.com/assets/6908839/3306215/df6c9af2-f65e-11e3-845e-7e6ff47f7d4f.png)

**Comment by imdfl** [comment]
Turning TC off now prompts the user to accept/reject pending changes.
