### ISSUE TITLE
Can end up with changes where the hilighting remains after accepting changes

### ISSUE THREAD

**Issue by trifprog** [loopindex/ckeditor-track-changes#29]
In Chrome, on your demo page,  after making multiple changes and accepting individual changes it has happened many times that one or more areas end up with hilighting that stay even after Accepting All.  
I have also captured a few other odd behaviors that I found in this testing session.  

Made a series of changes by multiple users:
![image](https://cloud.githubusercontent.com/assets/6908839/3343302/417a0392-f89e-11e3-9f52-b4e88a225a0d.png)

Accepting changes individually but this last one will not go away:
![image](https://cloud.githubusercontent.com/assets/6908839/3343311/5e6c30ce-f89e-11e3-8e98-49cfb8a0d102.png)

Tried Accept All and individually - you can see the right mouse options does not contain the correct actions:
![image](https://cloud.githubusercontent.com/assets/6908839/3343326/7c1dab2a-f89e-11e3-8417-2fae958dc182.png)

Here is the HTML Source - span tags remain:
![image](https://cloud.githubusercontent.com/assets/6908839/3343333/95368492-f89e-11e3-80a2-61693f355b0e.png)

Here is another sample, where I made a lot of separate changes, by multiple users, accepted some individually and then did Accept All and these two areas remained.  Hiding and Turning off still leave the hilighting.   Span tags in the HTML are like the previous example.
![image](https://cloud.githubusercontent.com/assets/6908839/3343361/ef77f1ac-f89e-11e3-9041-841020dfc309.png)

In testing I ran into these odd situations.  Here the 'Changed by David now' ended up in the actual document.  When the cursor hovers around the area the red indicators display.   
![image](https://cloud.githubusercontent.com/assets/6908839/3343384/1695852e-f89f-11e3-932f-b749b4236f50.png)

In this case the tooltips are layered on top of each other with two displaying at once.
![image](https://cloud.githubusercontent.com/assets/6908839/3343418/6fcc9510-f89f-11e3-8eb4-c9ab6699122f.png)

**Comment by imdfl** [comment]
Two flows that did end up with the described markup have been found and resolved. Marking as fixed, will close if no one is watching this.
