### ISSUE TITLE
IE8 problems with new tooltips

### ISSUE THREAD

**Issue by mrksctt** [loopindex/ckeditor-track-changes#32]
Using both mine and the demo version I get:

  'pageXOffset' is null or not an object  opentip-adapter.js, line 686 character 6
  Object doesn't support this property or method  opentip-adapter.js, line 1645 character 5

The errors seem to be related to the new tooltips. 

I changed the config to use the non-minified version to get the proper line numbers etc as follows:
    config.lite.tooltips = {
        show: true,
        path: "js/opentip-adapter.js", 
        classPath: "OpentipAdapter", 
        cssPath: "css/opentip.css", 
        delay: 500
    };

I see that opentooltips say that they support from IE7 and their demo page works OK with IE so. Any ideas where to start looking? Or is there a way to revert back to the old tooltips?

**Comment by imdfl** [comment]
To use the standard html tooltips, use the following configuration in you ckeditor config.js (or equivalent file/code):
````
	lite.tooltips = {
		show: true
	};
````
Omitting the classPath property from the tooltips configuration forces LITE to use standard html <code>title</code> elements.
Regardless of this feature, IE8 is not supported...
