### ISSUE TITLE
Licensing problem

### ISSUE THREAD

**Issue by Zimmi48** [loopindex/ckeditor-track-changes#34]
Hello,

I am considering using your library but I'm concerned that the licensing terms may be unlawful.

As I understand it, your plugin is based upon Ice (NYTimes). But the Ice library is distributed under the GPL v2.0. Unless you are not using the Ice code anymore (but the README says you are) or unless you got written agreements from all the copyright holders of Ice to sub-license their code (which is unlikely), you were not allowed to switch the license from GPL v2 to LGPL + MPL.

Maybe a solution would be to convince the authors of Ice to relicense it to MPL and LGPL. That would still be difficult however because it requires tracking down all the copyright holders (who could be many).

So I think the easiest thing to do is to switch back to GPL in order to comply with the Ice licensing terms.

**Comment by DevinCarlson** [comment]
I've been using Track Changes in a Drupal distribution that I'm working on. Since I'm using the Drupal.org packaging system, I'm only able to include libraries which are compatible with GPLv2 (which is what all code on Drupal.org must be licensed as, per the license policy: http://drupal.org/licensing/faq#q4).

Unfortunately, with the switch to LGPL + MPL, Track Changes is now unable to be bundled with Drupal projects (see the list of compatible licenses: http://drupal.org/node/1475972#whitelist-licenses).

It would be great to be able to use Track Changes with Drupal, Wordpress, etc!

**Comment by guytat** [comment]
Hi Devin,
We are still checking it, hoping to get back to you in the beginning of next week.

Thanks for getting in touch.
Cheers,
Guy.

**Comment by wojtekidd** [comment]
Any updates on the license issues? We would really like to add this plugin as one of [CKEditor's Add-on of the Month](http://ckeditor.com/blog/Add-on-of-the-Month). Please let me know!

Best regards!

**Comment by guytat** [comment]
The license has been update and we are now supporting three open source licenses (the re are many companies that take this approach - Mozilla, CKEditor and more).
Please reply if you have any concerns questions or comments, otherwise this issue will be closed in a week from today. 
Thanks.

**Comment by Zimmi48** [comment]
Hello,
In my opinion this does not solve the issue I raised initially: if you are still based on Ice and that you were not able to talk to the authors of the Ice plugin, then your own library can only be distributed under GPL v2 (not GPL v3 and not a dual or triple license).
However, IANAL and you should probably talk to a lawyer if you absolutely want to continue to use these licenses.
Best regards

**Comment by fredck** [comment]
Considering that this is based on Ice, there is not doubt that this plugin MUST be license under the GPL v2 terms, EXCLUSIVELY.

As for other comments, there is nothing like "virus" on licenses and that it would make the whole application automatically licensed as GPL. The CKEditor Track Changes plugin is simply breaching the GPL license of Ice, effectively not being legally allowed to use, link and redistribute it.

**Comment by guytat** [comment]
Thanks for your comments.
You are right, we should be GPL 2.0 only.
I've changed all the licensing to match the above.

Thanks again.

**Comment by Lyanra** [comment]
Please have a look at this request: #116 
It would be very much appreciated if someone could update to GPL2+

Thank you very much.
