### ISSUE TITLE
Undo Function Not Enabled When Only Removing Text

### ISSUE THREAD

**Issue by rgreco2** [loopindex/ckeditor-track-changes#42]
When track changes are on, removing existing text (not previously added or removed by user) by clicking backspace or delete leaves the undo function disabled.  Undo appears to only become available once you add text or perform some other snapshot generating function.  Once enabled, Ctrl+Z or hitting undo button allows you to undo everything, all the way back to the first text removal.

Using inline editor on contenteditable div.
![capture](https://cloud.githubusercontent.com/assets/11000506/6197659/6ec24614-b3b7-11e4-8d9f-581c11b488bf.PNG)

**Comment by imdfl** [comment]
Which version of CKEditor does this happen on? I tried the scenario on our [ demo page](http://www.loopindex.com/lite/demo/) , running CKE 4,4 mand undo was available from the firstr delete operation.

**Comment by imdfl** [comment]
Fixed in version 1.2.14
