### ISSUE TITLE
New span instead of old span extension width time update

### ISSUE THREAD

**Issue by artursmolarek** [loopindex/ckeditor-track-changes#44]
Is is possible to create new <span> with change when user add new text directly after text which was changed by him?
At the moment is possible only to track last change time, but I don't know what was exactly changed.

**Comment by imdfl** [comment]
LITE supports the notion of sessions and exposes an api that allows starting a new session. By default, all the time from the initialization of the editor until it is torn down, is considered one session. If you call the plugin's `startNewSession` method, all the edits from that moment on will not be grouped with previous edits from the same user.
