### ISSUE TITLE
Tooltip with change information cut off at the edge of the editor

### ISSUE THREAD

**Issue by tuhlmann** [loopindex/ckeditor-track-changes#46]
We are using the track changes plugin 1.1.30.
When we use ckeditor in full screen mode, the shown tooltip about the user and change info is cut off.
Please see the screenshots below:

Window Mode:
![undefined](https://cloud.githubusercontent.com/assets/407319/8041873/b67f4876-0e1b-11e5-9d6e-ab4a788d993b.png)

Full screen mode:
![undefined 2](https://cloud.githubusercontent.com/assets/407319/8041884/c693ff22-0e1b-11e5-84c2-b4377ffb55d7.png)

**Comment by imdfl** [comment]
If you can do without the fancy tooltips, then there's a way to configure LITE to use standard html title tags. Just add to your lite configuration (in config.js or wherever your configuration is, or dynamically after the `configLoaded` event) a block explicit properties for tooltips, omitting the classPath. 
e.g.:

````javascript
	lite.tooltips = {
		show: true,
		cssPath: "css/opentip.css",
		delay: 500
	};

''''

**Comment by tuhlmann** [comment]
Thanks, that seems to help, although I find the fancy tooltips much nicer :)
