### ISSUE TITLE
unable to delete footnotes (footnotes plugin)

### ISSUE THREAD

**Issue by cappe89** [loopindex/ckeditor-track-changes#49]
I'm working with the DEV version with the fix for the issue #47 and the lite and footnotes plugin enabled. Now it's possible to add footnotes correctly. 

With the configuration suggested by @imdfl 
ignoreSelectors = ["[data-track-changes-ignore]", "[data-footnote-id]", "section.footnotes"];
when i tried to delete the note the note is corretly removed but the trackchanges mark as removed the next character.

So I tried to change the configuration in this way:
ignoreSelectors = ["[data-track-changes-ignore]", "section.footnotes"];
When i tried to delete the note the trackchanges highlight the text as deleted but when I accept the changes the note is not removed.

**Comment by andykirk** [comment]
Hi,
I'm the author of the footnotes plugin.

I've also just noticed this problem - footnote widgets can't be moved or deleted (unless they already exist in the document and haven't already been moved).

Example: http://lab.gridlight-design.co.uk/ckeditor-4.4.7-footnotes/

I'm going to have a look to see if there's anything that can be done on my side to improve interoperability with this plugin (and possible others), though it may be something to do with how track-changes interacts with Widgets - I'll have to investigate to be sure.

Thanks,
Andy

**Comment by imdfl** [comment]
If the deletion is thru kbd de/backspace, then I'll have to introduce exceptions for some node types/attributes. Is this the scenario?

**Comment by andykirk** [comment]
Actually, it seems now that deleting the footnotes is ok, but it's moving them that's the problem.
Once they're moved, they become 'tracked' as in, they're wrapped in `ins` and that prevents them from being moved further, though the 'move' icon is still shown on hover. I assume something interferes with the widget upcast but not sure what yet. If I manually remove the `ins` wrapper through dev tools, the 'move' icon is not longer shown.

**Comment by andykirk** [comment]
Partial success:

`config.lite.ignoreSelectors = ["[data-track-changes-ignore]", ".cke_widget_wrapper"];` makes track changes completely ignore the footnote markers so they behave normally (move and delete).

Still looking into it ignore the Footnotes section, but that would seem to be a different issue.

**Comment by cappe89** [comment]
But there's no chance insert the note into trackchenges and reproduce the same behaivior of MS word?
