### ISSUE TITLE
Pasted text is not tracked

### ISSUE THREAD

**Issue by artursmolarek** [loopindex/ckeditor-track-changes#50]
I have empty editor and tracking enabled. When I am trying to paste any text from clipboard then this text is not marked as my change.

**Comment by imdfl** [comment]
Thank you for the report.
can you please list the steps to reproduce this problem on the [demo page](http://www.loopindex.com/lite/demo/) ?

**Comment by artursmolarek** [comment]
Sorry, that was problem with my configuration.
Issue can be closed.
