### ISSUE TITLE
Missing space in pending changes dialog

### ISSUE THREAD

**Issue by tuhlmann** [loopindex/ckeditor-track-changes#51]
There is a missing space between "contains" and "some" in the dialog:

![auswahl_076](https://cloud.githubusercontent.com/assets/407319/8777361/cfc51160-2ef7-11e5-8b39-a8045558ea78.png)

Apart from that, is there a way to make that text configurable so we could adapt it?

**Comment by imdfl** [comment]
Hope to add localisation support in the near future

**Comment by imdfl** [comment]
merged, closing
