### ISSUE TITLE
Not successful adding this plugin, have script error on load, help me to resolve

### ISSUE THREAD

**Issue by anemdhana** [loopindex/ckeditor-track-changes#54]
Discontiguous selection is not supported.(anonymous function) @ lite-includes.js:2(anonymous function) @ lite-includes.js:2(anonymous function) @ lite-includes.js:2w.init @ lite-includes.js:2F @ lite-includes.js:2b._initializeRangeLibrary @ lite-includes.js:2b @ lite-includes.js:2e.initializeEnvironment @ lite-includes.js:2e.startTracking @ lite-includes.js:2f._afterReady @ plugin.js?t=F74C:2
lite-includes.js:2 
'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).

**Comment by imdfl** [comment]
These are script warnings, not errors. They are generated from the Rangy library which LITE includes. This is harmless.

**Comment by jayrodkc** [comment]
I'm getting this issue too and it is an error. I'm running ckeditor 4.4.2 on Chrome Version 45.0.2454.101 (64-bit)

I've attached a screenshot.  
![screen shot 2015-10-14 at 7 41 53 am](https://cloud.githubusercontent.com/assets/4542830/10483922/9e71a9e6-7247-11e5-832d-fed628eb8f1f.png)

**Comment by imdfl** [comment]
Please see my prev reply

**Comment by howkins** [comment]
And I have too same error. Someone knows how to resolve this ?

![image](https://cloud.githubusercontent.com/assets/6891179/16643929/89847ae8-4421-11e6-8781-c4a93ada82ea.png)
