### ISSUE TITLE
Confirmation prompt before accept/reject

### ISSUE THREAD

**Issue by kiranparab0** [loopindex/ckeditor-track-changes#55]
Whenever user clicks on accept/reject changes, user should be prompted with confirmation box.
For this I have added below code, but this isn't working.

editor.on(LITE.Events.ACCEPT, function (e) {
                //code to open confirmation dialog will come here
                //.......
                return false;
            });
I tried with return false; assuming that it will not accept the changes, But its not behaving as expected.
I was searching for BeforeAccept event, but its not available.

**Comment by imdfl** [comment]
Hi,

What are you trying to accomplish? get a hook to the accept/reject so you can cancel the action?

**Comment by kiranparab0** [comment]
User can either cancel or continue the action.

**Comment by imdfl** [comment]
The accept/reject events are currently only for notification, they are not cancellable.  You are welcome to implement cancel checking, or leave this issue open until the feature is implemented.

**Comment by imdfl** [comment]
I took another look.
You can intercept the accept/reject commands by registering to ckeditor's `beforeCommandExec` event. In your event handler, check the command (either `event.data.name` or `event.data.command`) and apply whatever logic you want to decide whether or not to cancel it.

**Comment by kiranparab0** [comment]
Great!!! Thanks a lot.. That worked for me
