### ISSUE TITLE
Wrong delete on key press

### ISSUE THREAD

**Issue by cappe89** [loopindex/ckeditor-track-changes#56]
Selecting a word, or some text, after you press a button that is not a character, such as WIN or CTRL the seleted text is marked as deleted. The same error occurs if I do shift + click.

An example from the demo page (http://www.loopindex.com/lite/demo/)
![1](https://cloud.githubusercontent.com/assets/5970183/9111042/2bc81c5c-3c43-11e5-88ce-05bae61cf153.png)
the key SHIFT is pressed the result is
![2](https://cloud.githubusercontent.com/assets/5970183/9110963/95cad47e-3c42-11e5-8a98-b7a0ae04fd92.png)

**Comment by cappe89** [comment]
I found the fix: replace the function _handleSpecialKey in lite-includes.js with this code
```javascript
 _handleSpecialKey: function (e) {
            var keyCode = e.which;
            if (keyCode === null) {
                // IE.
                keyCode = e.keyCode;
            }

            var listSpeciaChar = [9, 16, 17, 18, 19, 27, 35, 36, 45, 91, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 144];
            if (listSpeciaChar.indexOf(keyCode) >= 0) {
                return true;
            }

            switch (keyCode) {
                case 120:
                case 88:
                    if (true === e.ctrlKey || true === e.metaKey) {
                        this.prepareToCut();
                        return true;
                    }
                    break;
                case 67:
                case 99:
                    if (true === e.ctrlKey || true === e.metaKey) {
                        this.prepareToCopy();
                        return true;
                    }
                    break;
                default:
                    // Not a special key.
                    break;
            } //end switch
            return false;
        },
```

**Comment by imdfl** [comment]
thanks. I'll go over the keycode list and integrate the fix.

**Comment by imdfl** [comment]
I think that the fix should not be placed where you've indicated. I implemented the sugggested change a bit differently. Currently on the dev branch, you're welcome to test and if fixed, close.
