### ISSUE TITLE
No way to disable CSS loading

### ISSUE THREAD

**Issue by dustyjewett** [loopindex/ckeditor-track-changes#60]
I'd rather not have a separate CSS file for this plugin, and include all of my CSS manually.  I'd like a way to prevent CSS from being automatically loaded.

**Comment by imdfl** [comment]
np, just note that when ckeditor runs in an iframe, you need to include your css through ckeditor's dedicated configuration properties.

**Comment by dustyjewett** [comment]
Yeah, that is what we do, we have all of our css driving through less to create one single contents.css. Definitely not for all users, but likely anyone making a javascript app will want to use their built-in css management, rather than the ad-hoc CSS loading.
