### ISSUE TITLE
No way to disable JS loading

### ISSUE THREAD

**Issue by dustyjewett** [loopindex/ckeditor-track-changes#65]
Advanced users want to load script files manually:

  * Ability to integrate with pre-existing build systems
  * Rangy and jQuery may already be loaded.
  * Developers don't want the LITE to noConflict() their jQuery.

**Comment by imdfl** [comment]
Just override the `lite.includes` configuration property.
see the api docs for details: http://www.loopindex.com/lite/docs/api/index.html#!/api/LITE.configuration

**Comment by dustyjewett** [comment]
Sorry, I had jumped to a conclusion that it was jQuery that was being overwritten and not working correctly... it's actually Selection that is overriding methods on rangy.
