### ISSUE TITLE
Joining lines with Backspace doesn't work when track changes are ON 

### ISSUE THREAD

**Issue by IvanaP** [loopindex/ckeditor-track-changes#7]
Enter two simple paragraphs
Place the cursor at the beginning of the second line and press Backspace - cursor position is now at the end on the first paragraph and lines are not joined. 
Does not occur with track changes off.

**Comment by imdfl** [comment]
This behavior is by design. Under track changes, you don't remove the newline mark, just mark it as deleted. Later you can accept the change, in which case the newline will be removed, or reject it.
