### ISSUE TITLE
Plugin does not "see" first change while shift key is pressed

### ISSUE THREAD

**Issue by dustyjewett** [loopindex/ckeditor-track-changes#71]
STR:
Open up demo.
Put cursor at end of first line.
Hold Shift, press "A".

Expected:
"A" is inserted, marked as an addition.

Actual:
"A" is inserted, not marked as an addition.

Letters after the first letter are marked as changes.

Browser Info: 
Chromium 43 on Linux

This issue seems browser specific, as it does not occur in Firefox latest.

**Comment by imdfl** [comment]
Which ckeditor version did this happen on?

**Comment by dustyjewett** [comment]
Latest. And also whatever version is being used here:
http://www.loopindex.com/lite/demo/

**Comment by sharabh** [comment]
Any update on the issue?

**Comment by imdfl** [comment]
As far as I can tell, this does not happen in Chrome, FF and IE. Can you please verify it's fixed, as we haven't got a linux machine to test on?
