### ISSUE TITLE
How to disable options from context menu

### ISSUE THREAD

**Issue by anemdhana** [loopindex/ckeditor-track-changes#72]
Hi,
I am able to disable few toolbar buttons for 'lite' plugin with the following.
lite.commands = [LITE.Commands.TOGGLE_SHOW];

And I want to disable the options from context menu as well. Pls suggest.

**Comment by imdfl** [comment]
Well, this seems to be a bug in LITE. Unavailable commands should not appear on the context menu. Will fix soon.

**Comment by imdfl** [comment]
Fixed, please verify
