### ISSUE TITLE
Feature request accept/reject changes by user selection

### ISSUE THREAD

**Issue by anemdhana** [loopindex/ckeditor-track-changes#73]
Hi,
From this, http://www.loopindex.com/lite/demo/
Is there a way to accept/reject only selected user's changes. May be toolbar buttons for this ?

We want to have this implemented, let me know the way to get the list of users involved in the current ckeditor content, so that on selecting particular user we can accept/reject only selected user's content.

**Comment by imdfl** [comment]
The acceptAll and rejectAll functions both take an optional <code>options</code> parameter. It can contain the following fields that allow you to select only some changes for accept/reject:

 * exclude: an array of user ids to exclude
  *include: an array of user ids to include
  *filter: a filter function of the form function({userid, time, data}):boolean.

**Comment by anemdhana** [comment]
Thanks, this helps.
And Is there a way I can add button to the 'lite' toolbar group, so I can bind some action on clicking this toolbar button. I want to bind to lite.acceptAll(excludedUserIds).

**Comment by imdfl** [comment]
you can listen to ckeditor's <code>beforeCommandExec</code>, intercept the lite acceptAll command, execute your own  code and cancel the event.
