### ISSUE TITLE
minified version

### ISSUE THREAD

**Issue by porjo** [loopindex/ckeditor-track-changes#74]
The zip file available from the Ckeditor plugins page (http://ckeditor.com/addon/lite) is not using minified files by default. `plugins.js` is unminified, and includes `lite-includes.js` (unless manually overridden to use `lite-includes.min.js`)

As that is where most end-users will get the plugin, shouldn't it be minified by default?

**Comment by imdfl** [comment]
You're right, this is a build error. Our builder generates a 'dist' folder with minified sources, somehow the zip contains parts of src. We'll fix, thanks for the catch.
