### ISSUE TITLE
track change does not working in Firefox

### ISSUE THREAD

**Issue by hptarora** [loopindex/ckeditor-track-changes#75]
Hi,
I am using it in Drupal 7. I have a page where I have a form with more than one editor and other input elements. The page is very long so every set of input elements and editors are collapsed and it expands on click.
The track changes does not work when I keep editor in collapsed form. But if I show simple editor on the form and not in collapsed form, then it works fine.
This problem is appearing only in Firefox and it works well in Safari no matter how the editor is placed on the form.
Could please help to resolve this issue.

Thanks

**Comment by imdfl** [comment]
Is there any console output you can share?
Is there a public link (or private, that you can share only with me) to a page that demonstrates the problem?

**Comment by hptarora** [comment]
I am working on local.
I can see following in the console
ICE plugin init: TypeError: sel.nativeSelection is null
console.error(args.join(' '));
Rangy warning: DEPRECATED: getIframeSelection() in module WrappedSelectionis deprecated. Please use getSelection(iframeEl) instead

Thanks

**Comment by hptarora** [comment]
Is anybody there to help me out.

thanks

**Comment by hptarora** [comment]
I figured out where the problem is but I dont know how to fix that.
In plugin.js following statement does not work in firefox when editor is in the collapsed form
this._tracker.startTracking();

Could you pls tell me what is alternate of this statement or why it is not working in Firefox.

Thank you

**Comment by imdfl** [comment]
By "collapsed", do you mean that the editors are run in inline mode, or that the toolbar is collapsed? Can you please share the code of the editor initialization?

**Comment by hptarora** [comment]
collapsed means when I display the form, I am using fieldset which contains the editor and other input elements. Fieldset is collapsed when shown on the form and on click it expands and shows the editor and other input element.
If I dont use put editor in fieldset and display it simply on the form then track changes works in Firefox.
But in Safari, it works even if I put editor in fieldset.
I was checking the code of track changes, in firefox it stucks at here this.initializeEnvironment(); in lite-includes.js when it initialize the environment at ice.selection, it get stuck and does not go beyond that.
For editor I am using drupal ckeditor module.
Please let me know if you need any other info.

Thank you

**Comment by imdfl** [comment]
Hi,

Do you know which versio of LITE is used in your system?
I tried starting LITE in a collapsed (`display=none`) div, didn't see any problems in chrome or FF. I'd like to help you, but your report doesn't contain any details which allow me to reproduce or even speculate on the nature of the problem.
If you could use the unminified latest dev version, the error output in the console would probably be very helpful.

**Comment by imdfl** [comment]
Thanks for the clarification.
As I wrote above, I tried running ckeditor in a collapsed (display=none) element and got no errors on FF in windows and os x. I have no access to a drupal system so I can't recreate your scenario. Once you have a public page running your setup and using unminified LITE, I'd be happy to check it out and offer my insight.

**Comment by hptarora** [comment]
Thank you for your reply.
I am using Version: 1.3alpha.804. I tried latest version as well but that also did not work moreover I found more problems with latest version.
I will have the public page soon and then I will send it to you.
Thank you

**Comment by hptarora** [comment]
Hi,
I am sorry, I can't share the link with you as per the policy.
I can provide you any in info which may help you to figure out the problem.
Please let me know.

Thank you
