### ISSUE TITLE
No "change" event when pasting text

### ISSUE THREAD

**Issue by tuhlmann** [loopindex/ckeditor-track-changes#76]
We listen on the change event that's emitted by the plugin. 

When I paste some text into the editor, the change event is fired when track changes is disabled, it is not fired when track changes is enabled.

Is there a workaround I could use?

**Comment by imdfl** [comment]
Just to be clear - do u mean the CKEditor change, or the LITE change event (`"lite:change"`)?

**Comment by tuhlmann** [comment]
@imdfl We only listen to CKEDITOR.on('change', ...). 
Should we switch listeners between that and "lie:change" depending on track changes beeing active?

**Comment by imdfl** [comment]
For now you can listen to `LITE.Events.CHANGE` (`"lite:change"`), but I plan to fix this in a few days.

**Comment by tuhlmann** [comment]
Great, thanks!

**Comment by tuhlmann** [comment]
@imdfl Is there any development on this issue?

**Comment by imdfl** [comment]
As far as I know it's resolved. 
Please check the dev branch (master also contains a solution but dev has a hopefully better one)

**Comment by tuhlmann** [comment]
Thank you, dev branch solves that problem.
