### ISSUE TITLE
how u acheived this <span reline attrs>text<br>test</span> inspite of <span reline attrs>text</span><br><span reline attrs>text</span>

### ISSUE THREAD

**Issue by Amara-Balakrishna1** [loopindex/ckeditor-track-changes#78]
on pressing enter we have two span nodes in default but u have only one span with two texts how is it possible.

**Comment by imdfl** [comment]
Well, I think you have an old version of LITE, since we've switched from <span> to <ins>/</del> a long time ago. In any case, you can do this programmatically, just append a <br/> node to a <span>
