### ISSUE TITLE
Punctuations are converted to special characters in IE.

### ISSUE THREAD

**Issue by ssmshah** [loopindex/ckeditor-track-changes#81]
1) Access the following link in IE11 http://www.loopindex.com/lite/demo/
2) Type , or . at the end of currently written statement
3) , will be converted to 1/4 and . will be converted to 3/4
![comma](https://cloud.githubusercontent.com/assets/16031351/11420982/89e83e3a-9453-11e5-8a99-3d74075e1e93.JPG)
![dot](https://cloud.githubusercontent.com/assets/16031351/11420990/90ac7812-9453-11e5-9ac7-12b5bc3a7632.JPG)

**Comment by imdfl** [comment]
Verified fixed in master and dev

**Comment by ssmshah** [comment]
https://github.com/loopindex/ckeditor-track-changes/issues/81#event-476988523
