### ISSUE TITLE
How to disable track changes of custom plugin

### ISSUE THREAD

**Issue by woutersplinter** [loopindex/ckeditor-track-changes#83]
Hi,

I've made a custom plugin in the CKEditor to insert own HTML href, but the lite track changes plugin create some double text. Now I want to disable track changes only for my custom plugin.

This appears only in Internet Explorer, when I type some text lite will mark this as an inserted text. After this I add a link with my custom plugin. After this I want apply the changes but the text I created a link stand now twice.

De standard plugin to create a link is not marked as a change by lite-plugin.

How to solve this?

Code:

    var selected_text;
    if (CKEDITOR.env.ie) {
        if (getInternetExplorerVersion() < 9) {
            editor.focus();
            selected_text = editor.getSelectedHtml();
        }
        else {
            selected_text = editor.getSelection().getSelectedText();
        }
    }
    else {
        selected_text = editor.getSelection().getNative();
    }
    editor.insertHtml('<a href=\"' + GetUrl() + '\">' + selected_text + '</a>', "unfiltered_html");
    $(this).dialog("destroy");

**Comment by imdfl** [comment]
Hi,

It should be easy to convince LITE to ignore your insertion. 
In your ckeditor config file, add the following lines (the first one may already exist):
````var lite = config.lite = config.lite || {};````
````// Various LITE configuration statements````
````lite.ignoreSelectors = ["[data-track-changes-ignore-id]"];````
(this will be done automatically in the upcoming version)

Then, in your code, add the attribute <code>data-track-changes-ignore</code> with some non-empty value to the html you're inserting, e.g.,
````editor.insertHtml('<a data-ckeditor-changes-ignore="ignore" href="' + GetUrl() + ' />' + selected_text + '</a>', "unfiltered_html");````
