### ISSUE TITLE
tracking changes in a sup element causes ckeditor to throw error

### ISSUE THREAD

**Issue by tuhlmann** [loopindex/ckeditor-track-changes#91]
We have this weird problem that for some changes that we track, when we try to accept them, ckeditor throws an error.

I have updated ckeditor to 4.5.6 and track-changes to the latest dev branch (today- 03.02.2016), though that problem happened also with cke 4.5.3.

This is the smallest possible html snippet I could come up with:

```
<div><p><sup><del class="ice-cts-1 ice-del" data-changedata="" data-cid="2" data-last-change-time="1454436172855" data-time="1454436172855" data-userid="52010a3184aeb9a46495e56b" data-username="TU">st</del></sup></p></div>
```

Past this as source into a ckeditor with change tracking enabled and then try to accept the change. This throws the following error for me:

```
TypeError: Cannot read property 'attributes' of null
    at ckeditor.js:1010
    at Object.CKEDITOR.htmlParser.fragment.forEach (ckeditor.js:279)
    at Object.CKEDITOR.htmlParser.fragment.forEach (ckeditor.js:279)
    at Object.CKEDITOR.htmlParser.fragment.forEach (ckeditor.js:279)
    at Object.CKEDITOR.htmlParser.fragment.forEach (ckeditor.js:279)
    at null.<anonymous> (ckeditor.js:1010)
    at q (ckeditor.js:10)
    at CKEDITOR.event.CKEDITOR.event.fire (ckeditor.js:12)
    at CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13)
    at Object.CKEDITOR.htmlDataProcessor.toDataFormat (ckeditor.js:301)
```

I've tried to run ckeditor in big'n'slow mode with uncompressed sources, but that seems to not work in our build configuration.

Any help greatly appreciated.

Thanks,
Torsten.

**Comment by imdfl** [comment]
Thanks for the detailed report. I'll try to reproduce.

**Comment by tuhlmann** [comment]
@imdfl The problem comes through a conflict with the footnotes plugin: https://github.com/andykirk/CKEditorFootnotes

Once this plugin is removed from the list `sup`-ed text does work again.

I tried to replicate this problem with `sub` and found that while the editor allows to click into the `sub` text, it didn't allowed this for the `sup`-ed text, instead it drew a rectangle around, possibly some functionality of the footnotes plugin.

Thanks,
Torsten.

**Comment by tuhlmann** [comment]
@imdfl The latest version of the footnotes plugin resolves this issue, I guess it limits what it treats as footnote boxes to a more specific markup.

**Comment by imdfl** [comment]
close ?

**Comment by tuhlmann** [comment]
Yeah, probably.
We ran into a similar but slightly different problem today with some other text.
Should that be lite related I'll open a new one.

Thanks for your support!
