### ISSUE TITLE
"containssome" missing space in pending changes dialog

### ISSUE THREAD

**Issue by meyeet** [loopindex/ckeditor-track-changes#95]
There is a misspelling in the pending changes dialog where "containssome" is missing a space between the two words.

**Comment by imdfl** [comment]
Thanks for the report. I could not find this misspelling, neither in the sources nor in the demo page.
Source: https://github.com/loopindex/ckeditor-track-changes/blob/master/src/lite/lang/en.js
Demo: http://www.loopindex.com/lite/demo/
