### ISSUE TITLE
Enabled track changes plugin breaks basic styles (strong, italic, ..)

### ISSUE THREAD

**Issue by porcinetdu07** [loopindex/ckeditor-track-changes#99]
Hi,

Use case is :
1. Enable track changes
2. Click on strong button (or other)
3. Type text
=> strong style is not applied, element path is reverted to previous

This issue can be reproduced in your demo page http://www.loopindex.com/lite/demo/.
No problem encountered by applying the style to a selection.

Thanks

**Comment by imdfl** [comment]
Thanks for the detailed report.
This issue is duplicate with #92
